### ISSUE TITLE
Needs version bumps

### ISSUE THREAD

**Issue by black-puppydog** [ssbc/scuttle-blog#3]
In patchwork this pulls in (via chloride et al.) an ancient version of sodium-native, which blocks upgrade of electron.
In general, dependabot might be a good idea.

**Comment by black-puppydog** [comment]
Upon further inspection, `ssb-keys` (which is the issue with this package for me) isn't actually needed... it isn't mentioned except in `package.json` and tests pass without it.
easy fix? :slightly_smiling_face:

**Comment by arj03** [comment]
Indeed :-)
